### ISSUE TITLE
Few languages and shorter commands.

### ISSUE THREAD

**Issue by javascripto** [basicBot/source#109]
So, i can translate into 2 more languages [Swedish, Lithuanian]. I did try to play around with your codes and thought that why not to make shorter commands. Like !clearchat into !clear or !cc.

**Comment by ItzLevvie** [comment]
"I did try to play around with your codes and thought that why not to make shorter commands. Like !clearchat into !clear or !cc."

you can make it as an alias if you want.

**Comment by javascripto** [comment]
Yeah but mostly people dont download the code. They just paste it in and use. While they do that they cant change a thing.
