### ISSUE TITLE
add custom command

### ISSUE THREAD

**Issue by BrownHat** [basicBot/source#121]
If i add command like this , will it run? I ask this question because when i run this command, nothing happen
![image](https://cloud.githubusercontent.com/assets/16576790/18359368/d3f0003c-7623-11e6-840d-8c4bf9a6fa81.png)

**Comment by BrownHat** [comment]
all custom cannot use but `!discord` can :s i dont know why 
![image](https://cloud.githubusercontent.com/assets/16576790/18359596/ce6d7f1c-7624-11e6-89ca-a82abbe8741f.png)

**Comment by ItzLevvie** [comment]
The first one should be ```bot.commands.moeCommand = {```
The second one should be ```bot.commands.fbCommand = {```
The third one should be ```bot.commands.discordCommand = {```

There ya go, problem solved ;)

**Comment by BrownHat** [comment]
i changed it, `!moe` `!fb` and `!discord` work, but `!yui` not work
![image](https://cloud.githubusercontent.com/assets/16576790/18374378/8c58753a-7676-11e6-949e-3e19a3178e49.png) 
![image](https://cloud.githubusercontent.com/assets/16576790/18374388/a39be4e8-7676-11e6-9a9f-8d0974371fb0.png) 
![image](https://cloud.githubusercontent.com/assets/16576790/18374394/ae90510e-7676-11e6-8a25-7d5202f6b103.png)

**Comment by BrownHat** [comment]
dont mind about this, can you teach me how i can put custom welcome message :D @ItzLevvie

**Comment by BrownHat** [comment]
oh, okay, i found it :3
