### ISSUE TITLE
Disable Autowoot

### ISSUE THREAD

**Issue by Beaupedia** [basicBot/source#122]
Hey there, how do we stop the bot from autowooting?

**Comment by ItzLevvie** [comment]
You can toggle autowoot from here https://github.com/basicBot/source/blob/master/basicBot.js#L259.

**Comment by Benchmaker** [comment]
@Beaupedia Why not just leave auto woot on and then make a woot/meh command for the bot?

**Comment by Trigstur** [comment]
Change this line

`258            autowoot: true,`

to

`258            autowoot: false,`

**Comment by Benzi** [comment]
https://github.com/basicBot/source/issues/122#issuecomment-270451338 I'll add those **Soon:tm:**

**Comment by Benchmaker** [comment]
https://github.com/basicBot/source/pull/134 @Benzi
