### ISSUE TITLE
W/M/G Edit?

### ISSUE THREAD

**Issue by Trigstur** [basicBot/source#130]
I was wondering if you could edit the stats display at the end of the song

https://github.com/basicBot/source/blob/master/basicBot.js#L965

**Comment by Benchmaker** [comment]
@Trigstur it should display at the end of song what do you mean?

**Comment by Trigstur** [comment]
@Benchmaker I tried editing it but it still displayed normal is there anyway i can edit it so it would display something else

**Comment by WiBla** [comment]
Two solutions:
1. Edit the source code from the [basicBot.js](https://github.com/basicBot/source/blob/master/basicBot.js) file to make it say what you want.
2. Fork the [custom](https://github.com/basicBot/custom) repository then edit its settings to use a custom [language file](https://github.com/basicBot/custom/blob/master/lang/en.json) and edit it.

**Comment by Benzi** [comment]
@WiBla Thanks!
