### ISSUE TITLE
$(customapi http://jwd.me/twitch/api/urban-dictionary.php?q=$(query)) ?

### ISSUE THREAD

**Issue by Trigstur** [basicBot/source#132]
`$(customapi http://jwd.me/twitch/api/urban-dictionary.php?q=$(query))` ?

**Comment by Benzi** [comment]
What?

**Comment by johand199** [comment]
i think he want a "!define <word>" command

example:
!define nope
Will connect to http://jwd.me/twitch/api/urban-dictionary.php?q=nope
and output "Slang for "no"." to the chat

**Comment by Trigstur** [comment]
I was wondering if api's whould work with query
